### ISSUE TITLE
frames

### ISSUE THREAD

**Issue by vendethiel** [yornaath/func-match#1]
Hi, and interesting component.

However I wanted to know what workaround you have for frames?

**Comment by yornaath** [comment]
There is none atm. But I will try to implement it if there is a need for one?

**Comment by vendethiel** [comment]
I often have this problem when dealing with userscripts. I'll get back to you when if I need it :). just wanted to know

**Comment by yornaath** [comment]
Well I could implement more robust instanceof checks for the native types. But Im not sure how I could test user types. Thoughts on that?

**Comment by vendethiel** [comment]
I think these usually don't suffer frames
